trigger:
  branches:
    include:
      - main  # O la rama en la que trabajes

pool:
  name: 'Default'  # El nombre del Agent Pool donde registraste tu agente self-hosted

variables:
  MY_GITHUB_TOKEN: $(GITHUB_TOKEN)  # Usar un nombre diferente para evitar referencias cíclicas

steps:
- script: |
    ansible-playbook -i ~/Documentos/Ansible/inventory.ini ~/Documentos/Ansible/deploy.yml
  displayName: 'Ejecutar Ansible Playbook localmente'
  env:
    ACTIONS_RUNTIME_TOKEN: $(MY_GITHUB_TOKEN)  # Usar el token de GitHub para evitar el límite de descargas

- script: |
    python3 /var/www/html/tests/test_selenium.py
  displayName: 'Ejecutar pruebas con Selenium'
