trigger:
  branches:
    include:
      - main  # O la rama en la que trabajes

pool:
  name: 'Default'  # El nombre del Agent Pool donde registraste tu agente self-hosted

variables:
  MY_GITHUB_TOKEN: $(GITHUB_TOKEN)  # Usar un nombre diferente para evitar referencias cíclicas

steps:
- script: |
    ansible-playbook -i ~/Documentos/Ansible/inventory.ini ~/Documentos/Ansible/deploy.yml
  displayName: 'Ejecutar Ansible Playbook localmente'
  env:
    ACTIONS_RUNTIME_TOKEN: $(MY_GITHUB_TOKEN)  # Usar el token de GitHub para evitar el límite de descargas

- script: |
    ssh azureuser@13.83.4.217 "ls -l /var/www/html/tests/"
    ssh azureuser@13.83.4.217 "python3 /var/www/html/tests/test_basicos.py"
  displayName: 'Listar archivos y ejecutar tests basicos con Selenium'

- script: |
    ssh azureuser@13.83.4.217 "ls -l /var/www/html/tests/"
    ssh azureuser@13.83.4.217 "python3 /var/www/html/tests/test_footer.py"
  displayName: 'Listar archivos y ejecutar tests unitario con Selenium'


